### ISSUE TITLE
No code in submission to "papers **with** code"

### ISSUE THREAD

**Issue by artdgn** [eitanrich/lin-im2im#1]
Does not signal much integrity / honesty.

**Comment by eitanrich** [comment]
I find this comment upsetting and unjustified since I did not submit to "papers with code" - the entry was created automatically after uploading the paper (which points to this repository) to arXiv.
Anyway, I hope to upload the code in the next couple of days.

**Comment by artdgn** [comment]
@eitanrich Sorry for using "submission" wording which implies deliberate action on your part. I do apologise for that.

It still may be a good idea to edit that automated entry manually (if you haven't yet) to not point to this repo for now, to prevent the confusing situation for anyone else.
